[package]
name = "noticopy"
version = "0.1.0"
authors = ["centos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4"
rm_rf = "0"
fs_extra = "1"